### ISSUE TITLE
libspatialindex 1.9.0

### ISSUE THREAD

**Issue by jwilson8767** [conda-forge/libspatialindex-feedstock#17]
@ocefpaf I have no idea how to help with these recipes, could you please incorporate 1.9.0? https://github.com/libspatialindex/libspatialindex/releases

Thanks!

**Comment by ocefpaf** [comment]
I remember tying the `rc` but got a few errors. I'll try the final release as soon as I get some free time.

**Comment by ocefpaf** [comment]
Done in #18
